//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindaSonrisa.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public BOLETA()
        {
            this.DETALLE = new HashSet<DETALLE>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.DateTime> HORA { get; set; }
        public string CLIENTE_RUT { get; set; }
        public string EMPLEADO_RUT { get; set; }
        public Nullable<decimal> VALOR_SERVICIO { get; set; }
        public Nullable<decimal> VALOR_PRODUCTO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<DETALLE> DETALLE { get; set; }
    }
}
