//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindaSonrisa.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMILIA_DE_PRODUCTOS
    {
        public FAMILIA_DE_PRODUCTOS()
        {
            this.TIPO_DE_PRODUCTO = new HashSet<TIPO_DE_PRODUCTO>();
        }
    
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<TIPO_DE_PRODUCTO> TIPO_DE_PRODUCTO { get; set; }
    }
}
