//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindaSonrisa.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODONTOLOGO
    {
        public ODONTOLOGO()
        {
            this.HORARIO = new HashSet<HORARIO>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public decimal ID_ODONTOLOGO { get; set; }
        public string RUT_EMPLEADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<HORARIO> HORARIO { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
