//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindaSonrisa.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENES_PRODUCTO
    {
        public decimal ID { get; set; }
        public string ID_PRODUCTO { get; set; }
        public decimal ID_ORDEN { get; set; }
    
        public virtual ORDEN_DE_PEDIDO ORDEN_DE_PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
