//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindaSonrisa.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_SERVICIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.DateTime> HORA { get; set; }
        public string CLIENTE_RUT { get; set; }
        public decimal ID_ODONTOLOGO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ODONTOLOGO ODONTOLOGO { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
