//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindaSonrisa.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.DETALLE = new HashSet<DETALLE>();
            this.HORARIO = new HashSet<HORARIO>();
            this.RESERVA = new HashSet<RESERVA>();
            this.SERVICIO_PRODUCTO = new HashSet<SERVICIO_PRODUCTO>();
        }
    
        public decimal ID_SERVICIO { get; set; }
        public string NOMBRE_SERVICIO { get; set; }
    
        public virtual ICollection<DETALLE> DETALLE { get; set; }
        public virtual ICollection<HORARIO> HORARIO { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        public virtual ICollection<SERVICIO_PRODUCTO> SERVICIO_PRODUCTO { get; set; }
    }
}
