//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindaSonrisa.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DE_PRODUCTO
    {
        public TIPO_DE_PRODUCTO()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public decimal FAMILIA_DE_PRODUCTOS_ID { get; set; }
    
        public virtual FAMILIA_DE_PRODUCTOS FAMILIA_DE_PRODUCTOS { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
