//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindaSonrisa.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public string NOMBRE { get; set; }
        public string PERFIL { get; set; }
        public string CONTRASENA { get; set; }
        public string EMPLEADO_RUT { get; set; }
        public string CLIENTE_R_P { get; set; }
        public string PROVEEDOR_RUT { get; set; }
        public Nullable<decimal> LOGIN { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
