//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindaSonrisaWPF.LSservicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LSservicio.IServicioLS")]
    public interface IServicioLS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLS/Validar", ReplyAction="http://tempuri.org/IServicioLS/ValidarResponse")]
        bool Validar(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLS/Validar", ReplyAction="http://tempuri.org/IServicioLS/ValidarResponse")]
        System.Threading.Tasks.Task<bool> ValidarAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLS/Leer", ReplyAction="http://tempuri.org/IServicioLS/LeerResponse")]
        string Leer(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLS/Leer", ReplyAction="http://tempuri.org/IServicioLS/LeerResponse")]
        System.Threading.Tasks.Task<string> LeerAsync(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioLSChannel : LindaSonrisaWPF.LSservicio.IServicioLS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioLSClient : System.ServiceModel.ClientBase<LindaSonrisaWPF.LSservicio.IServicioLS>, LindaSonrisaWPF.LSservicio.IServicioLS {
        
        public ServicioLSClient() {
        }
        
        public ServicioLSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioLSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Validar(string xml) {
            return base.Channel.Validar(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarAsync(string xml) {
            return base.Channel.ValidarAsync(xml);
        }
        
        public string Leer(string xml) {
            return base.Channel.Leer(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerAsync(string xml) {
            return base.Channel.LeerAsync(xml);
        }
    }
}
